language: java
jdk:
- oraclejdk8
before_install:
- unset _JAVA_OPTIONS
install:
- "./mvnw --version"
script:
- ./mvnw install
- sudo ./mvnw -Dtest=ServiceTest test
cache:
  directories:
  - "$HOME/.m2/"
after_success:
- if [ master == $TRAVIS_BRANCH -a $TRAVIS_PULL_REQUEST == false -a  ${OSSRH_USERNAME:=X}
  != X ]; then ./mvnw deploy -DskipTests=true --settings travis-settings.xml; fi
env:
  global:
  - secure: OMVtGcHnDpzUABwZk3ibYqJKZnDBxFu8T292SIsv8RkYqcgFXsYwRhT16NoZxDmPK8U6eLItIIfl3DeYFJxFgJm6mIQtkHr2AObSvWq9bjByCVvWFmcinUtLYIaWh7xxIETabxqBI3z5nXffwYUXIPnsEWZ11qf9LVwsCLiPhB/AvARybM8kFQME3pnTgQnbYCEK0cJmBzItgBKIvQ6GWgjaDzN+lIyaNKqL01kryaHIKBBVolp0tvcCUvK110QDHv3rz4tb2p1ayS0XM1DonLhx/3fkBw354vQ+yx1oNxhvyOgXAOcvkG8mAjVlI5QmgMq1P2gqA9tmfUFh+Ko8H+19/atgldGOrSG4UA4p6dfLrb1npe1ixK+lPGe81QiomRthIbYazIYVJDS5OGjSmwnMGIKT/rOcHn5o6ci5EJ/veC0NvU3pLiSwxeELUZaLWgv7C8BBy2yPSsfTibN9C8Vuf+5xRHvoAylWP81iknT3BNmdBOSuBh0M2gu6vf7EPvx3f1qxt1mB74yZKqS1iMQP4/aKWHCEt4bmZLM7OFzlZHAwQdnctpXHnMIJXMyMqdgpqA40Hf10Iz+oOnIwP95O1PmKLq1bf5DvBeLFqO4gRayBSG4u/wGeEGyPziuO0yduojTOl5z+cOSKYat/HEFXIgnVThc1TTZzlCdDPUI=
  - secure: V82m99B14as/WGhn8HANuaLI/XjPguUzOW/r9HmO24Ck7EASXWin4xxkJXArcNdtWNG+7LIbfYf/OiTROCcdyRl8UYAvJN8gqNhvbQ+9Oap/AqmVvMk9nGgAW0JDxwNQijpGzitHyOlsPfo34jNMew05gm6RZ5CANqh3BBzzeH0F0lKTCZrXDYJWMI80sWW3wTPn/G0jCUslXred9oSYVl+JqLip4Rqq7Z2JPQA82RD6RAFnyXlU4C1vWOaM/0y/y9SGkRdQZTnx/mNkE4JZqCcGQKmQ4jJHieHNNWUBoWmTyrRQtFdfGiESPS64Ehtnxcp6r0+nlUhppT9QvYcdbXi4WQjnQA8TDD6NitstuScxY3nstwl55oKgd5jdRx+kYwWmUIIjrcUljvffNO3GCRvocFwcFOe3L75Yy8qyasQASsHON/cFkZqBcJ/g7JUh/VzTXryUgjhsJxtfEDxah3bKfgJC2BOjkSn5zldFqDq8ml2vRbcfd+X95paTN27YL9WgRbYFk64DU9Ii+cefGLGv2gnRSjBP+UDlFI8lJejy2Tlg8wqdpiO6mnty1u2sl0ubF+iySWJAoIzQCn9sLWoONtCEtETk6+kRtdVZocTbpKh1hrdbpl+XtaJ7flQH/3H2iMUGNgcIPeXkGtPD3ePM2SENa7SRh/HTf+4gY30=
