version: '{build}'

clone_depth: 50

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - mvnw.cmd --version

build_script:
  - mvnw.cmd install

cache:
  - C:\Users\appveyor\.m2
